services:
  app:
    build: .
    ports:
      - "8080:8080"
    env_file:
      - .env
    environment:
      - SPRING_PROFILES_ACTIVE=prod
    depends_on:
      db:
        condition: service_healthy
    restart: always
    networks:
      - gapms-network

  db:
    image: mysql:8.0
    ports:
      - "3307:3306"
    env_file:
      - db.env
    volumes:
      - mysql-data:/var/lib/mysql
    restart: always
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - gapms-network

volumes:
  mysql-data:

networks:
    gapms-network:
        driver: bridge