spring:
  config:
    activate:
      on-profile: prod
  datasource:
    url: jdbc:mysql://${AZURE_HOST}:${AZURE_PORT}/${AZURE_DB_NAME}?useSSL=true&requireSSL=false&serverTimezone=UTC&useLegacyDatetimeCode=false
    username: ${AZURE_NAME}
    password: ${AZURE_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    generate-ddl: false
    hibernate:
      ddl-auto: none
    show-sql: false
  # Security configuration
  security:
    user:
      name: ${SECRET_USER}
      password: ${SECRET_PASSWORD}
    oauth2:
      client:
        registration:
          google:
            client-id: ${GOOGLE_CLIENT_ID}
            client-secret: ${GOOGLE_CLIENT_SECRET}
            scope: profile,email
            redirect-uri: https://gapms-aha3aphhh0fna2dx.southeastasia-01.azurewebsites.net/login/oauth2/code/google
        provider:
          google:
            authorization-uri: https://accounts.google.com/o/oauth2/auth
            token-uri: https://oauth2.googleapis.com/token
            user-info-uri: https://www.googleapis.com/oauth2/v3/userinfo
            jwk-set-uri: https://www.googleapis.com/oauth2/v3/certs
  # Email configuration
  mail:
    host: smtp.gmail.com
    port: 587
    username: ${MAIL_USER}
    password: ${MAIL_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
  # Thymeleaf cache bật trong môi trường production để tăng hiệu suất
  thymeleaf:
    cache: true
  # Flyway configuration

logging:
  level:
    root: ERROR
    org.springframework: WARN
    fpt.g36.gapms: INFO
  file:
    name: /tmp/gapms.log
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} - %msg%n"
    file: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"
